name: Playtimes
version: "${version}"
main: me.codedred.playtimes.PlayTimes
author: Cmaaxx
authors: [CodedRed]
softdepend: [PlaceholderAPI]
description: Check Players PlayTime And More!

commands:
  playtime:
    aliases: [playt, playerinfo, pt]
    description: "Check your playtime!"
    usage: "/playtime"
  uptime:
    aliases: [serveruptime, serverupt]
    description: "Check your servers uptime!"
    usage: "/uptime"
  topplaytime:
    aliases: [topplayt, toppt]
    description: "Check your servers uptime!"
    usage: "/topplaytime"
